### ISSUE TITLE
Excellent work, but I have a question: why are the tokens in the image shifted by one position?

### ISSUE THREAD

**Issue by bruce2233** [apartresearch/Integer_Addition#1]
![image](https://github.com/apartresearch/Integer_Addition/assets/54824693/6dc0155e-0bb2-4317-8f64-0adf51743838)

A3 should be the sum of D3 and D3'. But in the column in Figure1.C and Figure1.B, A3 is the sum of D2 and D2'. 

Thanks!

**Comment by PhilipQuirke** [comment]
Hi there. The model is an auto-regressive transformer. The 6 digit answer is predicted, token by token, from left (A5) to right (A0).  At each answer token position it is predicting the _next_ answer token. The A3 prediction needs to be calculated _before_ the A3 step. We find the A3 value is predicted in the _preceding_ (A4) column. In the A4 column, we see D3 and D3' being "summed" 9 as you expected) in the 3rd (green) head labelled 'Addition mod 10'. The A3 answer prediction is completed in the A4 position.
